# render.yaml
services:
  - type: web
    name: ai-chatbot-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
    envVars:
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    rootDir: backend