services:
  - type: web
    name: ai-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    rootDir: .
    envVars:
      - key: GROQ_API_KEY
        fromEnv: GROQ_API_KEY